#!/bin/sh

# this is supposed to be the repository directory
repository_directory=$(pwd)

# create bin directory if it does not exist
if [ ! -d "$HOME/bin" ]; then
    mkdir $HOME/bin
fi

# copy bin files to bin folder
cp $repository_directory/bin/* $HOME/bin/

# copy scripts to bin folder
cp $repository_directory/scripts/* $HOME/bin

# gives execution grants to every file contained inside bin
chmod +x $HOME/bin/*
